# Generated by Django 6.1 on 2026-08-29 09:36

import django.core.validators
import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, help_text='Upload a profile picture (JPEG, PNG, or WebP up to 5MB).', null=True, upload_to='profile_pictures/%Y/%m/', validators=[users.models.validate_image_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('bio', models.TextField(blank=True, default='', help_text='Tell readers a bit about yourself (max 500 characters).', max_length=500, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
